---
- name: Install CA certificate package
  ansible.builtin.package:
    name: ca-certificates
    state: present
  tags:
    - minimal

- name: Ensure certificate authority file is present
  ansible.builtin.get_url:
    dest: "{{ ca_path }}/{{ item.name }}"
    group: root
    mode: "0444"
    owner: root
    url: "{{ item.url }}"
  loop: "{{ base_certauth }}"
  tags:
    - minimal
  when:
    - not ansible_check_mode   # (Bug ansible/ansible#65687)

- name: Update trusted certificate authorities
  ansible.builtin.command: "{{ base_update_trust_cert }}"
  changed_when: false
  when:
    - not ansible_check_mode
  tags:
    - minimal
