---
- name: Ensure my base DEB packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"
  tags:
    - minimal

- name: Ensure additional DEB packages are installed (on Ubuntu < 20.04 and any other systems).
  ansible.builtin.apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')
  tags:
    - minimal

- name: Ensure additional DEB packages are installed (on Ubuntu >= 20.04).
  ansible.builtin.apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')
  tags:
    - minimal

- name: Update APT cache and upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: "{{ 'latest' }}"  # Yes, redundant, but necessary to not anger the lint gods...
    update_cache: true

- name: Remove useless APT packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove APT dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
