---
- name: Ensure fail2ban is installed from EPEL repository (RedHat).
  ansible.builtin.package:
    name: fail2ban
    state: present
    enablerepo: epel
  when: ansible_os_family == 'RedHat'

- name: Ensure fail2ban is installed (Debian)
  ansible.builtin.package:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy fail2ban custom configuration file
  ansible.builtin.template:
    src: "{{ base_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: Ensure fail2ban is running and enabled on startup
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
