---
- name: Ensure virtualization kernel packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ base_kernel_package_install }}"
  notify: Update GRUB

- name: Ensure non-virtualization kernel packages are removed
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ base_kernel_package_remove }}"
  notify: Update GRUB

- name: Check if NOOP scheduler is configured in the boot command
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*elevator=noop'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: Ensure NOOP scheduler is used when running under virtualization
  ansible.builtin.lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 elevator=noop"'
  notify: Update GRUB
  when: grub_cmdline_check.found == 0

- name: Retrive service facts
  ansible.builtin.service_facts:

- name: Disable Hyper-V services when not using a Hyper-V hypervisor
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - hv-kvp-daemon.service
  when:
    - ansible_bios_version is not match("Hyper-V UEFI")
    - ansible_facts.services[item]is defined
