---
- name: Include tasks specific to Ubuntu.
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Ensure non-virtualization kernel packages are removed.
      ansible.builtin.apt:
        name: "{{ item }}"
        autoremove: true
        purge: true
        state: absent
      loop:
        - linux-headers-generic
        - linux-generic
        - linux-tools-generic
        - linux-cloud-tools-generic
        - linux-firmware

    - name: Ensure virtualization kernel packages are installed.
      ansible.builtin.apt:
        name: "{{ item }}"
        install_recommends: true
        state: present
      loop:
        - linux-virtual
        - linux-tools-virtual
        - linux-cloud-tools-virtual
      notify: Update GRUB

- name: Check if NOOP scheduler is configured in the boot command.
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*elevator=noop'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: Ensure NOOP scheduler is used when running under virtualization.
  ansible.builtin.lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 elevator=noop"'
  notify: Update GRUB
  when: grub_cmdline_check.found == 0

- name: Disable Hyper-V services on non-Hyper-V hypervisors.
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - hv-kvp-daemon.service
  when: ansible_bios_version is not match("Hyper-V UEFI")
