---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Update YUM cache
  ansible.builtin.yum:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "yum"

- name: Update APK cache
  community.general.apk:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apk"

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "dnf"
