---
- name: Update YUM package cache
  ansible.builtin.yum:
    update_cache: true
  changed_when: false
  when:
    - not ansible_check_mode
  tags:
    - minimal

- name: Ensure custom distribution packages are installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages_distribution }}"

- name: Upgrade all packages
  ansible.builtin.yum:
    name: "*"
    state: "{{ 'latest' }}"
  when:
    - not ansible_check_mode

- name: Remove package dependencies that are no longer required
  ansible.builtin.yum:
    autoremove: true
  when:
    - not ansible_check_mode
