---
- name: Ensure EPEL installed
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - minimal

- name: Ensure my base RPM packages are installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"
  tags:
    - minimal

- name: Update YUM Cache and Upgrade all RPM Packages
  ansible.builtin.yum:
    name: "*"
    state: "{{ 'latest' }}"  # Yes, redundant, but necessary to not anger the lint gods...
    update_cache: true

- name: Remove RPM dependencies that are no longer required
  ansible.builtin.yum:
    autoremove: true
