---
- name: Ensure EPEL installed on CentOS and RHEL
  ansible.builtin.yum:
    name: epel-release
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_pkg_mgr == "yum"
  tags:
    - minimal

- name: Execute YUM package management related tasks
  when: ansible_pkg_mgr == "yum"
  block:
    - name: Update YUM cache
      ansible.builtin.yum:
        update_cache: true
      changed_when: false
      when:
        - not ansible_check_mode
      tags:
        - minimal

    - name: Ensure custom RPM packages are installed
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ base_packages }}"
      tags:
        - minimal

    - name: Upgrade all RPM packages
      ansible.builtin.yum:
        name: "*"
        state: "{{ 'latest' }}"
      when:
        - not ansible_check_mode

    - name: Remove RPM dependencies that are no longer required
      ansible.builtin.yum:
        autoremove: true
      when:
        - not ansible_check_mode

- name: Execute DNF package management related tasks
  when: ansible_pkg_mgr == "dnf"
  block:
    - name: Update DNF cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when:
        - not ansible_check_mode
      tags:
        - minimal

    - name: Ensure custom RPM packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ base_packages }}"
      tags:
        - minimal

    - name: Upgrade all RPM packages
      ansible.builtin.dnf:
        name: "*"
        state: "{{ 'latest' }}"
      when:
        - not ansible_check_mode

    - name: Remove RPM dependencies that are no longer required
      ansible.builtin.dnf:
        autoremove: true
      when:
        - not ansible_check_mode
