---
- name: Ensure SSH daemon is enabled and running
  ansible.builtin.service:
    enabled: true
    name: "{{ base_ssh_name }}"
    state: started

- name: Ensure SSH server configuration
  ansible.builtin.lineinfile:
    dest: "{{ base_ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: sshd -T -f %s
    mode: "0644"
  loop:
    - regexp: "^AllowAgentForwarding"
      line: "AllowAgentForwarding {{ 'yes' if base_ssh_allow_agent_forwarding else 'no' }}"
    - regexp: "^AllowTcpForwarding"
      line: "AllowTcpForwarding {{ 'yes' if base_ssh_allow_tcp_forwarding else 'no' }}"
    - regexp: "^ClientAliveInterval"
      line: "ClientAliveInterval {{ base_ssh_client_alive_interval }}"
    - regexp: "^ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication {{ 'yes' if base_ssh_challenge_response_auth else 'no' }}"
    - regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication {{ 'yes' if base_ssh_gss_api_authentication else 'no' }}"
    - regexp: "^LoginGraceTime"
      line: "LoginGraceTime {{ base_ssh_login_grace_time }}"
    - regexp: "^MaxSessions"
      line: "MaxSessions {{ base_ssh_max_sessions }}"
    - regexp: "^MaxAuthTries"
      line: "MaxAuthTries {{ base_ssh_max_auth_tries }}"
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication {{ 'yes' if base_ssh_password_authentication else 'no' }}"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords {{ 'yes' if base_ssh_permit_empty_password else 'no' }}"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin {{ 'yes' if base_ssh_permit_root_login else 'no' }}"
    - regexp: "^Port"
      line: "Port {{ base_ssh_port }}"
    - regexp: "^PrintLastLog"
      line: "PrintLastLog {{ 'yes' if base_ssh_print_last_log else 'no' }}"
    - regexp: "^PrintMotd"
      line: "PrintMotd {{ 'yse' if base_ssh_print_motd else 'no' }}"
    - regexp: "^Protocol"
      line: "Protocol 2"
    - regexp: "^PubkeyAuthentication"
      line: "PubkeyAuthentication {{ 'yes' if base_ssh_public_key_authentication else 'no' }}"
    - regexp: "^UseDNS"
      line: "UseDNS {{ 'yes' if base_ssh_usedns else 'no' }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding {{ 'yes' if base_ssh_x11_forwarding else 'no' }}"
  notify: Restart SSH
