---
- name: Ensure logging package is installed
  ansible.builtin.package:
    name: "{{ base_logging_package }}"
    state: present

- name: Ensure logging forwarding rules are configured
  ansible.builtin.template:
    src: remotelog.conf.j2
    dest: /etc/rsyslog.d/remotelog.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Syslog
