---
- name: Update GRUB
  ansible.builtin.shell: /usr/sbin/update-grub
  notify: Reboot Host

- name: Reboot Host
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Restart Journal
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ base_journal_services }}"

- name: Restart SSH
  ansible.builtin.service:
    name: "{{ base_ssh_name }}"
    state: restarted

- name: Restart Syslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Update trusted certificate authorities
  ansible.builtin.command:
    cmd: "{{ base_update_trust_cert }}"
