---
- name: Reboot Host
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Restart SSH
  ansible.builtin.service:
    name: "{{ base_ssh_name }}"
    state: restarted

- name: Restart Syslog
  ansible.builtin.service:
    name: "{{ base_logging_service }}"
    state: restarted

- name: Update GRUB
  ansible.builtin.shell: /usr/sbin/update-grub
  notify: Reboot Host
